In [1]:
import numpy as np

In [2]:
np.array([2,3,4,5,6])

array([2, 3, 4, 5, 6])

In [3]:
type(np.array([2,3,4,5,6]))

numpy.ndarray

In [4]:
np.array([[2,3,4],[4,5,6]])

array([[2, 3, 4],
       [4, 5, 6]])

In [5]:
l=[[12,3,4],[4,5,6]]

In [6]:
l

[[12, 3, 4], [4, 5, 6]]

In [7]:
l[0]

[12, 3, 4]

In [8]:
l[0][0]

12

In [9]:
l[0][2]

4

In [10]:
a = np.array([3,4,5,6], ndmin= 5 )

In [11]:
a

array([[[[[3, 4, 5, 6]]]]])

In [12]:
arr = np.array([[1,2,3],[4,5,6], [7,8,9]])

In [13]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr.ndim

2

In [15]:
np.random.randint(1,10,(4,4))

array([[1, 3, 9, 1],
       [7, 6, 7, 8],
       [2, 3, 5, 4],
       [9, 3, 3, 1]])

In [16]:
np.random.randint(1,10,(4,4,2))

array([[[8, 3],
        [2, 5],
        [8, 3],
        [1, 8]],

       [[7, 5],
        [7, 7],
        [7, 8],
        [7, 5]],

       [[2, 6],
        [3, 7],
        [3, 9],
        [1, 6]],

       [[5, 3],
        [7, 3],
        [9, 8],
        [8, 2]]])