In [1]:
import numpy as np 

In [2]:
l = [1,2,3,4,5,6]

In [3]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [4]:
l1 = [4,5,6,7,"sudh" , 34.565, True]

In [9]:
a1= np.array(l1)

In [6]:
a2 = np.array([[1,2,3] , [4,5,6]])

In [7]:
a3 = np.array([[[1,2,3] , [4,5,6] , [7,8,9]]])

In [10]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [11]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [13]:
a1.ndim

1

In [14]:
a2.ndim

2

In [15]:
a3.ndim

3

In [16]:
a1.size

7

In [17]:
a2.size

6

In [18]:
a3.size

9

In [19]:
a1.shape

(7,)

In [21]:
a2.shape

(2, 3)

In [22]:
a3.shape

(1, 3, 3)

In [23]:
np.random.randint(2,50 ,(3,4) )

array([[24,  2, 23,  3],
       [48,  6,  5, 44],
       [23, 41, 29, 19]])

In [24]:
np.random.randint(2,50 ,(2,3,4) )

array([[[41, 42, 28, 13],
        [30, 31, 33, 41],
        [12,  5, 28,  2]],

       [[26,  8, 17, 25],
        [32, 48, 27,  9],
        [ 3, 21, 16, 45]]])

In [25]:
np.random.rand(5,4)

array([[0.24621601, 0.9742297 , 0.74317623, 0.8170941 ],
       [0.77372369, 0.35905744, 0.00546653, 0.46322756],
       [0.8292298 , 0.77000895, 0.97803457, 0.22519358],
       [0.898006  , 0.73673526, 0.90711875, 0.18094363],
       [0.53770569, 0.55101064, 0.58622748, 0.85808169]])

In [26]:
a4 =  np.random.randn(4,4)

In [29]:
a4

array([[ 0.09087136, -0.89299395,  0.76578574,  0.80104104],
       [-0.06517541,  0.15296423,  0.97342916,  0.48991336],
       [ 1.11601548,  1.66045121,  0.08839625, -1.07574615],
       [-0.14539179,  0.57113492, -0.82353852,  0.57176938]])

In [27]:
a4.ndim

2

In [28]:
a4.reshape(2,8)

array([[ 0.09087136, -0.89299395,  0.76578574,  0.80104104, -0.06517541,
         0.15296423,  0.97342916,  0.48991336],
       [ 1.11601548,  1.66045121,  0.08839625, -1.07574615, -0.14539179,
         0.57113492, -0.82353852,  0.57176938]])

In [30]:
a4.reshape(8,2)

array([[ 0.09087136, -0.89299395],
       [ 0.76578574,  0.80104104],
       [-0.06517541,  0.15296423],
       [ 0.97342916,  0.48991336],
       [ 1.11601548,  1.66045121],
       [ 0.08839625, -1.07574615],
       [-0.14539179,  0.57113492],
       [-0.82353852,  0.57176938]])

In [31]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [32]:
a1[0]

'4'

In [34]:
a1[1:4]

array(['5', '6', '7'], dtype='<U32')

In [35]:
a1[1:5:2]

array(['5', '7'], dtype='<U32')

In [36]:
a1[::4]

array(['4', 'sudh'], dtype='<U32')

In [37]:
a1[::-1]

array(['True', '34.565', 'sudh', '7', '6', '5', '4'], dtype='<U32')

In [38]:
a5 = np.random.randint(2,90 , (6,5))

In [39]:
a5

array([[ 8, 62, 29, 25, 82],
       [89, 87, 20, 56,  5],
       [11, 73,  6, 67, 58],
       [22, 40, 42, 76, 16],
       [40, 79, 15, 20, 37],
       [ 9, 72, 29, 20, 54]])

In [40]:
a5[a5>30]

array([62, 82, 89, 87, 56, 73, 67, 58, 40, 42, 76, 40, 79, 37, 72, 54])

In [41]:
a6 = np.random.randint(0,3 , (3,3))

In [42]:
a7 = np.random.randint(0,3 , (3,3))

In [43]:
a6

array([[1, 1, 1],
       [0, 1, 0],
       [2, 2, 0]])

In [44]:
a7

array([[2, 2, 2],
       [1, 2, 0],
       [0, 0, 1]])

In [45]:
a6*a7

array([[2, 2, 2],
       [0, 2, 0],
       [0, 0, 0]])

In [46]:
a6+a7

array([[3, 3, 3],
       [1, 3, 0],
       [2, 2, 1]])

In [47]:
a6-a7

array([[-1, -1, -1],
       [-1, -1,  0],
       [ 2,  2, -1]])

In [48]:
a6@a7

array([[3, 4, 3],
       [1, 2, 0],
       [6, 8, 4]])

In [49]:
a6+200

array([[201, 201, 201],
       [200, 201, 200],
       [202, 202, 200]])

In [50]:
a6*2

array([[2, 2, 2],
       [0, 2, 0],
       [4, 4, 0]])

In [51]:
a6**2

array([[1, 1, 1],
       [0, 1, 0],
       [4, 4, 0]], dtype=int32)

In [52]:
a8 = np.zeros((4,4))

In [53]:
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [54]:
a9 = np.ones((4,4))

In [55]:
a9+10

array([[11., 11., 11., 11.],
       [11., 11., 11., 11.],
       [11., 11., 11., 11.],
       [11., 11., 11., 11.]])

In [56]:
a9/10

array([[0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1]])

In [57]:
np.sqrt(a5)

array([[2.82842712, 7.87400787, 5.38516481, 5.        , 9.05538514],
       [9.43398113, 9.32737905, 4.47213595, 7.48331477, 2.23606798],
       [3.31662479, 8.54400375, 2.44948974, 8.18535277, 7.61577311],
       [4.69041576, 6.32455532, 6.4807407 , 8.71779789, 4.        ],
       [6.32455532, 8.88819442, 3.87298335, 4.47213595, 6.08276253],
       [3.        , 8.48528137, 5.38516481, 4.47213595, 7.34846923]])

In [58]:
np.exp(a5)

array([[2.98095799e+03, 8.43835667e+26, 3.93133430e+12, 7.20048993e+10,
        4.09399696e+35],
       [4.48961282e+38, 6.07603023e+37, 4.85165195e+08, 2.09165950e+24,
        1.48413159e+02],
       [5.98741417e+04, 5.05239363e+31, 4.03428793e+02, 1.25236317e+29,
        1.54553894e+25],
       [3.58491285e+09, 2.35385267e+17, 1.73927494e+18, 1.01480039e+33,
        8.88611052e+06],
       [2.35385267e+17, 2.03828107e+34, 3.26901737e+06, 4.85165195e+08,
        1.17191424e+16],
       [8.10308393e+03, 1.85867175e+31, 3.93133430e+12, 4.85165195e+08,
        2.83075330e+23]])

In [59]:
list(range(0,10 , 2))

[0, 2, 4, 6, 8]

In [60]:
np.arange(1.8,10.7,2.5)

array([1.8, 4.3, 6.8, 9.3])

In [61]:
np.linspace(2,3,num=50,retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [62]:
import cufflinks as cf 
import numpy as np
import pandas as pd 
import seaborn as sns

In [63]:
!pip install cufflinks

In [64]:
cf.go_offline()

In [65]:
df = pd.DataFrame(np.random.randn(100,3),columns=['A' , 'B' ,'C'])

In [66]:
df

A         B         C
0  -0.573249  0.580242 -1.476825
1   0.753391 -1.300947 -0.696309
2   0.018581  0.149118  0.915562
3   2.085667 -0.145910  0.254939
4  -1.165072 -0.924558  0.116378
..       ...       ...       ...
95  0.477163  0.666049 -0.247479
96 -1.689350 -0.005246 -3.349913
97  0.637127  1.772108 -1.389839
98 -1.142270  0.989181  0.407605
99 -0.563615 -0.663916  0.076853

[100 rows x 3 columns]

In [67]:
df.iplot()

In [68]:
df1 = pd.DataFrame(np.random.randint(3,100,(100,1)))

In [69]:
df1.iplot()

In [70]:
df.iplot(x = 'A' , y = 'B',mode = 'markers')

In [71]:
df2 = sns.load_dataset('titanic')

In [72]:
df2

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [73]:
df2.iplot(x = 'age' , y ='fare',mode = 'markers' )