In [2]:
import numpy as np
my_array=np.array([10,12,14,16,20,25])
print(my_array)
print(my_array.dtype)
print(my_array.dtype.itemsize)

[10 12 14 16 20 25]
int32
4


In [3]:
import numpy as np
my_array=np.array(["Red","Green","Orange"])
print(my_array)
print(my_array.dtype)
print(my_array.dtype.itemsize)

['Red' 'Green' 'Orange']
<U6
24


In [4]:
import numpy as np
my_array=np.array(["1990-10-04","1989-05-06","1990-11-04"])
print(my_array)
print(my_array.dtype)
print(my_array.dtype.itemsize)

['1990-10-04' '1989-05-06' '1990-11-04']
<U10
40


In [6]:
my_array3=my_array.astype("M")
print(my_array3.dtype)
print(my_array3.dtype.itemsize)

datetime64[D]
8


In [7]:
import numpy as np
my_array=np.array(["1990-10-04","1989-05-06","1990-11-04"], dtype="M")
print(my_array)
print(my_array.dtype)
print(my_array.dtype.itemsize)

['1990-10-04' '1989-05-06' '1990-11-04']
datetime64[D]
8


In [8]:
nums_arr= np.arange(5,12,2)
print(nums_arr)

[ 5  7  9 11]


In [9]:
ones=np.ones(7)
ones

array([1., 1., 1., 1., 1., 1., 1.])

In [12]:
# We also can create two dimension array using ones, given below :-

ones_2=np.ones((4,4))
ones_2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
# Zeros() method is used to create a numpy array of zeros, given below :-

zero_array=np.zeros(5)
zero_array

array([0., 0., 0., 0., 0.])

In [15]:
# We can also create a two dimensional array using zeroes just to mention row and column mentioned below :-

zeros_array = np.zeros((6,4))
print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
# random.randint() method is used to create a numpy array with random integars between a certain range. 
# The first perimiter specifies the lower bound whereas second parameter specifies the upper bound and 
# The last parameter specifies the number of random integars to generate between the range.

integer_random=np.random.randint(10,50,5)
print(integer_random)

[49 37 33 38 35]


In [19]:
# ndim is used to see the dimension of that array and for shape, shape attribute is used.

print(zeros_array.ndim)
print(zeros_array.shape)

2
(6, 4)


In [20]:
for i in zeros_array:
    print(i)

[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]


In [21]:
# The below script creates a two dimensional numpy array with four rows and
# five columns. The array contains random inegers between 1 and 10.

integer_random = np.random.randint(1,11, size=(4,5))
print(integer_random)

[[ 8  9  8  7  7]
 [ 6  6  2 10  1]
 [ 7  3  9  2  8]
 [ 6  3  2  6  4]]
