### Numpy_Practise

1. Delete multiple items from an array.
2. Delete a row or column from a 2-D array using the delete method.
3. To delete a column, you can set the value of the axis attribute to 1.
4. Sort NumPy arrays of various types.
5. Sort a text array with the NumPy sort() method.
6. Sort the Boolean arrays in NumPy.
7. Sort two-dimensional arrays.
8. Sort an array in descending order.
9. Modify the shape of a NumPy array.

In [1]:
# If you want to deleter multiple items for an arry just pass the iterm index in the form of a list to the delete() method.

import numpy as np
my_array = np.array(["Red","Green","Orange"])
print(my_array)
print("After deletion")
updated_array = np.delete(my_array, [1,2])
print(updated_array)

['Red' 'Green' 'Orange']
After deletion
['Red']


In [2]:
import numpy as np
integar_random = np.random.randint(1,11, size=(4,5))
print(integar_random)
print("After deletion")
updated_array = np.delete(integar_random,1,axis=0 )
print(updated_array)

[[ 5  1  5  1  3]
 [ 3 10  9  3  1]
 [ 7  2  8  9  2]
 [ 1  7  8  6  1]]
After deletion
[[5 1 5 1 3]
 [7 2 8 9 2]
 [1 7 8 6 1]]


In [3]:
import numpy as np
integar_random = np.random.randint(1,11, size=(4,5))
print(integar_random)
print("After deletion")
updated_array = np.delete(integar_random, 1 ,axis=1 )
print(updated_array)

[[ 6  1  4  5  9]
 [10  2  8  4  4]
 [ 8  1 10 10  6]
 [ 1  2  9  7  6]]
After deletion
[[ 6  4  5  9]
 [10  8  4  4]
 [ 8 10 10  6]
 [ 1  9  7  6]]


In [4]:
import numpy as np
print("unsorted array")
integar_random = np.random.randint(1,20,10)
print(integar_random)
print("\nSorted array")
updated_array = np.sort(integar_random)
print(updated_array)

unsorted array
[15 15  9 12 18 19 11 13 11 19]

Sorted array
[ 9 11 11 12 13 15 15 18 19 19]


In [5]:
import numpy as np
print("unsorted array")
my_array = np.array(['Red','Green','Yellow','Blue'])
print(my_array)
print("\nSorted array")
sorted_array = np.sort(my_array)
print(sorted_array)

unsorted array
['Red' 'Green' 'Yellow' 'Blue']

Sorted array
['Blue' 'Green' 'Red' 'Yellow']


In [6]:
print("One dimensional array")
one_array = np.random.randint(1,20,10)
print(one_array)
print("\nTwo dimensional array")
two_array = one_array.reshape(2,5)
print(two_array)

One dimensional array
[ 3  2  8 11 15  7 19 19 12 16]

Two dimensional array
[[ 3  2  8 11 15]
 [ 7 19 19 12 16]]


1. To load a NumPy array in the “NPY” format, you can use the load() method.
2. If your NumPy array is stored in the text form, you may use the loadtxt() method to load such a NumPy array.
3. To find the mean or average of all the items in a NumPy array, you need to pass the array to the mean() method of the NumPy module.
4. Find the mean in a two-dimensional NumPy array across rows and columns.
5. The median() method from the NumPy module is used to find the median value in a NumPy array.
6. To find the median values across columns and rows in a two dimensional array, you need to pass 1 and 0, respectively, as the values for the axis attribute of the median method.
7. The max() function returns the maximum value from the array, while the min() function returns the minimum value.
8. You can get the minimum values across all rows or columns in a two dimensional NumPy array by passing 0 or 1 as values for the axis attribute of the min() method.
9. To get the maximum value from a NumPy array, you may use the max() method.
10. You can get the maximum values across all rows or columns in a two-dimensional NumPy array by passing 0 or 1 as values for the axis attribute of the max() method.

In [7]:
import numpy as np
my_array = np.array([2,3,4,5,6,7,8])
print(my_array)
print("mean:")
print(np.mean(my_array))

[2 3 4 5 6 7 8]
mean:
5.0


In [8]:
import numpy as np
my_array = np.random.randint(1,20, size = (2,3))
print(my_array)
print("mean:")
print(np.mean(my_array, axis = 1))
print(np.mean(my_array, axis = 0))

[[16  1  8]
 [ 9  8  5]]
mean:
[8.33333333 7.33333333]
[12.5  4.5  6.5]


In [9]:
import numpy as np
my_array = np.array([2,4,6,8,10])
print(np.median(my_array))

6.0


In [10]:
import numpy as np
my_array = np.random.randint(1,20, size = (2,3))
print(my_array)
print("median:")
print(np.median(my_array, axis = 1))
print(np.median(my_array, axis = 0))

[[ 1  2 11]
 [ 3 17  5]]
median:
[2. 5.]
[2.  9.5 8. ]


In [11]:
import numpy as np
my_array = np.array([2,4,6,8,10])
print(my_array)
print("min value:")
print(np.min(my_array))

[ 2  4  6  8 10]
min value:
2


In [12]:
import numpy as np
my_array = np.array([2,4,6,8,10])
print(my_array)
print("max value:")
print(np.max(my_array))

[ 2  4  6  8 10]
max value:
10


1. The standard deviation of a NumPy array can be found via the std() method.
2. To find the standard deviation across rows and columns in a two-dimensional NumPy array, you need to call the std() method.
3. Finally, to find correlations, you can use the correlation() method and pass it the two NumPy arrays between which you want to find the correlation.
4. To find unique values in a NumPy array, you need to pass the array to the unique() method from the NumPy module.
5. To find the count of every unique item in a NumPy array, you need to pass the array to the unique() method and pass True as the value for the return_counts attribute.
6. One way to get the count value against every unique item is to create an array of arrays where the first item is the list of unique items and the second item is the list of counts.
7. you can transpose the array that contains the list of unique items and their counts.
8. There are two main methods to reverse a NumPy array: flipud() and fliplr().
9. To reverse a two-dimensional NumPy array, you can use the fliplr() method.

In [13]:
my_array = np.array([2,4,6,8,10])
print(my_array)
print("Standard Deviation")
print(np.std(my_array))

[ 2  4  6  8 10]
Standard Deviation
2.8284271247461903


In [15]:
import numpy as np
my_array = np.random.randint(1,20, size = (3,4))
print(my_array)
print("Standard Deviation")
print(np.std(my_array, axis = 1))
print(np.std(my_array, axis = 0))

[[14  8 16 11]
 [14 19 15 15]
 [ 7 19  2  1]]
Standard Deviation
[3.03108891 1.92028644 7.15454401]
[3.29983165 5.18544973 6.37704216 5.88784058]


In [16]:
# Correlations() method used to find out correclations.
a1 = np.array([1,2,3,4,5,3])
a2= np.array([2,3,1,4,3,5])
print(a1)
print(a2)
print("Correlation value:")
print(np.correlate(a1,a2))

[1 2 3 4 5 3]
[2 3 1 4 3 5]
Correlation value:
[57]


In [19]:
import numpy as np
a1 = np.array([12,11,1,2,3,4,5,11,23,34,43,13,23])
print(np.unique(a1))

[ 1  2  3  4  5 11 12 13 23 34 43]


In [20]:
import numpy as np
a1 = np.array([12,11,1,2,3,4,5,11,23,34,43,13,23])
unique_items, counts = np.unique(a1, return_counts = True)
print(np.unique(a1))
print(counts)

[ 1  2  3  4  5 11 12 13 23 34 43]
[1 1 1 1 1 2 1 1 2 1 1]


In [21]:
import numpy as np
print("Original")
my_array = np.random.randint(1,20,10)
print(my_array)
print("reversed")
reversed = np.flipud(my_array)
print(reversed)

Original
[17 15 18  9  3 14 18 13  8  1]
reversed
[ 1  8 13 18 14  3  9 18 15 17]
